version: '3.9'
services:
  znuny:
    image: mgcred/znuny
    container_name: znuny_app
    volumes:
      - ./skin/Agent:/opt/otrs/var/httpd/htdocs/skins/Agent/mgcred
      - ./skin/Customer:/opt/otrs/var/httpd/htdocs/skins/Customer/mgcred
      - ./skin/CustomSkin.xml:/opt/otrs/Kernel/Config/Files/CustomSkin.xml
      - ./Template:/opt/otrs/Kernel/Output/HTML/Templates/MGCred
    ports:
      - 80:80
    depends_on:
      - database
    networks:
      - mgcred-srv

  database:
    image: mgcred/znuny-mariadb
    container_name: znuny_db
    expose:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    networks:
      - mgcred-srv
      

networks:
  mgcred-srv: